version: "3.9"
services:
  db-communications:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - src/.env
    ports:
      - "5434:5432"
    networks:
      - mc_network
  web-communications:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8200
    volumes:
      - ./src:/app/src
    ports:
      - "8200:8200"
    networks:
      - mc_network
    depends_on:
      - db-communications
networks:
  mc_network:
    external: true
